name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.0
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        env:
          CI: true
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build-prod

      - name: Package
        run: bash ./scripts/package.sh ${{ env.VERSION }}

      - uses: actions/upload-artifact@v2
        name: Upload archive
        with:
          name: dark-mode-plugin-${{ env.VERSION }}
          path: build
          if-no-files-found: error
          retention-days: 10
