name: automation-create-a-release

on:
  push:
    branches:
      - master

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.0
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        env:
          CI: true
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build-prod

      - name: Package
        run: bash ./scripts/package.sh ${{ env.VERSION }}

      - uses: actions/upload-artifact@v2
        name: Upload archive
        with:
          name: dark-mode-plugin-${{ env.VERSION }}
          path: build
          if-no-files-found: error
          retention-days: 10

      - uses: hainguyenvan6799/automation-build-and-release@1.0.1
        id: release

      - name: Upload assets to release
        if: ${{ steps.release.outputs.released == 'true' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./archive/dark-mode-plugin-1.0.0.zip
          asset_name: dark-mode-plugin.zip
          asset_content_type: application/zip

